spring.application.name=auth-service
server.port=8081
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.redis.autoconfigure.RedisVectorStoreAutoConfiguration
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
