spring:
  application:
    name: infra-notify-services
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info
